language: node_js
node_js:
- '6'
script: echo 'winning'
after_success: npm run build
deploy:
  provider: lambda
  region: eu-west-1
  function_name: pennies-front-door-dogfood
  role: arn:aws:iam::447737720704:role/pennies-front-door-travis
  zip: build.zip
  handler_name: index.handler
  access_key_id: AKIAJFSSDGJNEXKK3J6Q
  secret_access_key:
    secure: N+wVVITi3nClgLrX4DQovfBOCGLsBoe/Kc4nQpQac+1Z0M/Dl3+6PJgDH2lOnsoadHKe8fK6+rH4b9dygxHPb0TaAussur9lqhhUMq0A3uEogRr+zRm+3p3jY1iwVV/KHOeogxUWuWyyxek8e1WhLUA4Znsr+MKLaLp9pUlP9aV3XIFnWXKSZwbQyHr8sx0qFuozpDGUc9OoVxqvbkvVWUvbzYJzRb0vddyB7Fg2e6RHwcXjkbEtzYiEkroESNgR0OLHBmlNJBvzJ0wx3IYXiOmHJFp/EtQVhpddxxBX/nJZo8vaLAv/UT7SbaryFX/Kpa3YbP2+RZasGbOLzKGm4n/km7hPcCdPrqqXXmWOsyt2QnVQR6p+NMBE0UZ8X2O68hmcOEhk+OZ2s0B2CLAq06QcK5kcbnq+Jrf9Yz02FMyEpKqvWexcRDRAjF/xb7NdJpNqkbLW93yVLnCbwxfMHF8TogIKE3iXpDSywtKtzXPVlkp7vftBDRJW//zRmsGIWw1VeehZnldRAD2FRPLsy3NME5dXMw0lLbeoFaLI8h//681z74mqQD9po1/dJjzTDtVetq6IFO8BBtcmjkHoDLntcV1uHS6A+R6GFhBScZ5YrZ4eAsnXI2LheMYU4Y7Qdd3vd4Q3TKaM5X7NKM9Ul146giQ0Vst9xhNbID+sYZE=
